#!/usr/bin/perl -w

use strict;
use warnings;
use Data::Dumper;
use Workout::Calc;
use Workout::Store::SRM;
use Workout::Store::HRM;
use Workout::Join;
use Workout::Resample;
use Getopt::Long;

my $itype;
my $otype;
my $recint = 5;

my $needhelp;
my $wanthelp;

if( ! GetOptions(
	"help|h!"	=> \$wanthelp,
	"input|i=s"	=> \$itype,
	"output|o=s"	=> \$otype,
	"recint|r=i"	=> \$recint,
)){
	$needhelp++;
}

if( $wanthelp ){
	print <<EOF;
$0 [opt] <input file> <output file>
convert workout files between formats

--help              this help
--input|-i=<type>   input file type
--output|-o=<type>  input file type
--recint|-r=<int>   sampling interval (default=5)

for now only conversion from .srm to .hrm is supported
EOF
	exit 0;
}

if( @ARGV != 2 ){
	print STDERR "in- and output filename required\n";
	$needhelp++;
}

if( $needhelp ){
	print STDERR "use --help for usage info\n";
	exit 1;
}
	
my( $ifile, $ofile ) = @ARGV;

my $calc = Workout::Calc->new;
my $src = Workout::Store::SRM->new( $ifile, { 
	calc => $calc,
} );
my $join = Workout::Join->new( $src, { 
	calc => $calc,
} );
my $res = Workout::Resample->new( $join, { 
	calc => $calc, 
	recint => $recint,
} );
my $dst = Workout::Store::HRM->new( $ofile, { 
	calc => $calc, 
	recint => $recint, 
	write => 1,
} );
$dst->from( $res );
$dst->flush;

