#!/usr/bin/perl -w
#
# Copyright (c) 2008 Rainer Clasen
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms described in the file LICENSE included in this
# distribution.
#

# TODO: pod

use strict;
use warnings;
use Workout;
use Getopt::Long;
use I18N::Langinfo qw(langinfo CODESET);

my $charset = langinfo(CODESET);
binmode STDIN, ":encoding($charset)";
binmode STDOUT, ":encoding($charset)";
binmode STDERR, ":encoding($charset)";



my $itype;

my $opt_start;
my $opt_note;
my $opt_sport;
my $opt_slope;
my $opt_circum;
my $opt_zeropos;
my $opt_athletename;

my $debug;
my $needhelp;
my $wanthelp;

if( ! GetOptions(
	'athlete!'	=> \$opt_athletename,
	'circum!'	=> \$opt_circum,
	'help!'		=> \$wanthelp,
	'itype=s'	=> \$itype,
	'note!'		=> \$opt_note,
	'sport!'		=> \$opt_sport,
	'slope!'	=> \$opt_slope,
	'start!'	=> \$opt_start,
	'zeropos!'	=> \$opt_zeropos,
)){
	$needhelp++;
}

if( $wanthelp ){
	print <<EOF;
$0 [opt] <input file>
print workout details

Options:
--start             start time in seconds since 1970-1-1
--note              workout note
--sport             workout sport

--slope             get slope (SRM)
--circum            get wheel circumference (SRM)
--zeropos           get zero offset (SRM)
--athlete           get athlete name (SRM)

--debug             enable debuging output
--help              this help
EOF
	exit 0;
}

if( @ARGV != 1 ){
	print STDERR "you need to specify a single input file\n";
	$needhelp++;
}

if( $needhelp ){
	print STDERR "use --help for usage info\n";
	exit 1;
}

my $fname = shift;

my $src = Workout::file_read( $fname, {
	ftype	=> $itype,
	debug	=> $debug,
} );

if( $opt_start ){
	print $src->time_start, "\n";
}

if( $opt_note ){
	print $src->note, "\n";
}

if( $opt_sport ){
	print $src->sport, "\n";
}

if( $opt_slope ){
	$src->can('slope') || die "slope is unsupported";
	printf "\%.1f\n", $src->slope;
}

if( $opt_circum ){
	$src->can('circum') || die "circum is unsupported";
	print $src->circum, "\n";
}

if( $opt_zeropos ){
	$src->can('zeropos') || die "zeropos is unsupported";
	print $src->zeropos, "\n";
}

if( $opt_athletename ){
	$src->can('athletename') || die "athletename is unsupported";
	print $src->athletename, "\n";
}

