#!/usr/bin/perl -w

use strict;
use warnings;
use Workout;
use Getopt::Long;


my $debug;
my $itype;

my $needhelp;
my $wanthelp;

if( ! GetOptions(
	"debug!"	=> \$debug,
	"input|i=s"	=> \$itype,
	"help|h!"	=> \$wanthelp,
)){
	$needhelp++;
}

if( $wanthelp ){
	print <<EOF;
$0 [opt] <input file>
dump workout file as tab seperated list

--debug             enable debuging output
--help              this help
--input|-i=<type>   input file type

for now only .srm files are supported
EOF
	exit 0;
}

if( @ARGV != 1 ){
	print STDERR "you need to specify a single input file\n";
	$needhelp++;
}

if( $needhelp ){
	print STDERR "use --help for usage info\n";
	exit 1;
}

my $ifile = shift;

my $src = Workout::file_read( $ifile, {
	ftype	=> $itype,
	debug	=> $debug,
} );

# TODO: allow user to specify fields he wants to be dumped
#my @fields = qw( time dur dist spd cad hr work pwr);
my @fields = qw( time dur spd pwr ele );
my $iter = $src->iterate;
#my $iter = 
#	Workout::filter( 'Resample', 	# TODO
#	Workout::filter( 'Join', $src ),	# TODO
#	{ recint => 5 } );

print join("\t", @fields), "\n";
while( my $r = $iter->next ){
	print join("\t", map { $r->$_ || 0 } @fields), "\n";
}
